---
config:
  layout: elk
---
flowchart TD
 subgraph FA["Calculate Rule Activation 'w_i'"]
    direction LR
        F2@{ label: "Get Membership 'm_0'" }
        F1["Start activationCalc(rule, inputs)"]
        F3["activation = m_0"]
        F4{"Loop Antecedents (k=1 to numAntecedents-1)"}
        F5@{ label: "Get Membership 'm_k'" }
        F6["activation = applyOperator(rule.op, activation, m_k)"]
        F7{"rule.op == AND and activation == 0?"}
        F9["Return activation = 0"]
        F8["Return activation"]
  end
    A["Start evaluate(inputs, numInputs, &resultValue, outputVarIndex)"] --> B{"Validate Inputs?"}
    B -- OK --> C["Init weightedSum=0, weightSum=0, ruleFired=false"]
    B -- Error --> Z["Return Error Code"]
    C --> D{"Loop Through Rules (i = 0 to ruleCount-1)"}
    D --> E{"Rule[i].consequentVarIndex == outputVarIndex?"} & M{"ruleFired == true?"}
    E -- Yes --> F@{ label: "Calculate Rule Activation 'w_i'" }
    E -- No --> D
    F --> G{"w_i > 0?"}
    G -- Yes --> H@{ label: "Get Consequent MF 'mf_c' from Rule[i]" }
    G -- No --> D
    H --> I@{ label: "Calculate Centroid 'c_i' = getMfCentroid(mf_c)" }
    I --> J["weightedSum += w_i * c_i"]
    J --> K["weightSum += w_i"]
    K --> L["Set ruleFired = true"]
    L --> D
    M -- No --> N["resultValue = default (e.g., var.min)"]
    N --> O["Return FUZZY_ERROR_NO_RULES_FIRED"]
    M -- Yes --> P{"abs(weightSum) &lt; epsilon?"}
    P -- Yes --> Q["resultValue = default (e.g., var.min)"]
    Q --> R["Return FUZZY_ERROR_DIVIDE_BY_ZERO"]
    P -- No --> S["resultValue = weightedSum / weightSum"]
    S --> T["Constrain resultValue to outputVar min/max"]
    T --> U["Return FUZZY_OK"]
    F1 --> F2
    F2 --> F3
    F3 --> F4
    F4 -- Next Antecedent --> F5
    F5 --> F6
    F6 --> F7
    F7 -- Yes --> F9
    F7 -- No --> F4
    F4 -- Loop Finished --> F8
    O --> Z
    R --> Z
    U --> Z
    F@{ shape: rect}
    H@{ shape: rect}
    I@{ shape: rect}
    F2@{ shape: diamond}
    F5@{ shape: diamond}
